library(tidyverse)
library(cowplot)
# library(edgeR)
# library(DESeq2)
# library(sgRSEA)
# library(PBNPA)
library(readr)
library(ggsci)
library(here)
#library(CC2Bench)
library(pheatmap)
library(RColorBrewer)
library(GGally)
library(Cairo)


set_here()

source("R/util.R")
source("R/heatmap_fdr.R")
source("R/heatmap_legend.R")
source("R/lineplot_fdr.R")

#source("scripts/download-nbt3536.R")
load("inst/extdata/nature-biotech.Rdata")
#source("scripts/run-benchmarks.R")
source("scripts/benchmarks-gene.R")
source("scripts/benchmarks-sgRNA.R")
