library(tidyverse)
library(cowplot)
library(edgeR)
library(DESeq2)
library(sgRSEA)
library(PBNPA)
library(plotROC)
library(PRROC)
library(readr)
library(ggsci)
library(here)
library(CC2Sim)
library(pheatmap)
library(RColorBrewer)


set_here()
source("scripts/download-nbt3536.R")
source("scripts/run-benchmarks.R")
source("scripts/benchmarks-gene.R")
source("scripts/benchmarks-sgRNA.R")
