library(tidyverse)
library(cowplot)
library(readr)
library(edgeR)
library(DESeq2)
library(sgRSEA)
library(PBNPA)
library(plotROC)
library(PRROC)
library(ggsci)
library(here)
library(CC2Bench)
library(pheatmap)
library(RColorBrewer)
library(GGally)
library(Cairo)


#set_here()
#source("scripts/download-nbt3536.R")
load("inst/extdata/nature-biotech.Rdata")
#source("scripts/run-benchmarks.R")
source("scripts/benchmarks-gene.R")
source("scripts/benchmarks-sgRNA.R")
